apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GimhanDissanayake/DevSecOps-AWS.git
    targetRevision: main
    path: helm/charts/auth-service
    helm:
      valueFiles:
        - ../../values/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
