apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
  # WHY finalizer: Ensures ArgoCD cleans up K8s resources when the Application is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GimhanDissanayake/DevSecOps-AWS.git
    targetRevision: main
    path: helm/charts/order-service
    helm:
      valueFiles:
        - ../../values/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true      # WHY: Deletes resources removed from Git
      selfHeal: true   # WHY: Reverts manual changes made outside Git
    syncOptions:
      - CreateNamespace=true
