name: CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/**'

# WHY minimal permissions: Default is read-only. Each job requests only what it needs.
permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, user-service, order-service, notification-service]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache-dependency-path: apps/${{ matrix.service }}/go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: apps/${{ matrix.service }}

      - name: Test
        run: go test ./...
        working-directory: apps/${{ matrix.service }}

  build-and-push:
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC auth to AWS
      contents: read
    strategy:
      matrix:
        service: [auth-service, user-service, order-service, notification-service]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t ${{ steps.ecr.outputs.registry }}/devsecops-aws/${{ matrix.service }}:sha-${{ github.sha }} apps/${{ matrix.service }}/

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ steps.ecr.outputs.registry }}/devsecops-aws/${{ matrix.service }}:sha-${{ github.sha }}
          format: 'table'
          exit-code: "1"
          severity: HIGH,CRITICAL

      - name: Push to ECR
        run: |
          docker push ${{ steps.ecr.outputs.registry }}/devsecops-aws/${{ matrix.service }}:sha-${{ github.sha }}
